var TILE_COUNT = 3;
var TILE_SIZE = 64;

var CANVAS_WIDTH = (TILE_SIZE * TILE_COUNT);
var CANVAS_HEIGHT = (TILE_SIZE * TILE_COUNT);

var DEFAULT_CANVAS_COLOR = 'black';//'rgb(83,86,44)';

var BOARD_LEFT_OFFSET = (CANVAS_WIDTH / 2) - (TILE_SIZE * (TILE_COUNT / 2));
var BOARD_TOP_OFFSET = (CANVAS_HEIGHT / 2) - (TILE_SIZE * (TILE_COUNT / 2));
var BOARD_RIGHT_MARGIN = (BOARD_LEFT_OFFSET + (TILE_SIZE * TILE_COUNT));
var BOARD_BOTTOM_MARGIN = (BOARD_TOP_OFFSET + (TILE_SIZE * TILE_COUNT));

var TILE_FONT = '14px Lucida Console';

var RANDOM_STEPS = TILE_COUNT * 500;
var ANIMATION_TIMEOUT = 5;