const TILE_COUNT = 4;
const CANVAS_WIDTH = 640;
const CANVAS_HEIGHT = 480;
const TILE_SIZE = 64;
const DEFAULT_CANVAS_COLOR = 'black';//'rgb(83,86,44)';

const BOARD_LEFT_OFFSET = (CANVAS_WIDTH / 2) - (TILE_SIZE * (TILE_COUNT / 2));
const BOARD_TOP_OFFSET = (CANVAS_HEIGHT / 2) - (TILE_SIZE * (TILE_COUNT / 2));
const BOARD_RIGHT_MARGIN = (BOARD_LEFT_OFFSET + (TILE_SIZE * TILE_COUNT));
const BOARD_BOTTOM_MARGIN = (BOARD_TOP_OFFSET + (TILE_SIZE * TILE_COUNT));

const TILE_FONT = 'bold ' + (TILE_SIZE/5) +'px Courier';

const RANDOM_STEPS = TILE_COUNT * 80;
const ANIMATION_TIMEOUT = 5;